### ISSUE TITLE
Please add an open_source license to this project

### ISSUE THREAD

**Issue by srichardbd** [endocrimes/buildkite-gcp-scaler#5]
Hi there @endocrimes,

Is it possible to add a license to this project? I was reading the below site and made it seem like using this code might be problematic unless there was an explicit open source license.

https://choosealicense.com/no-permission/

potentially the MIT license?

https://choosealicense.com/licenses/mit/

pull_request to add one is here https://github.com/endocrimes/buildkite-gcp-scaler/pull/6

**Comment by endocrimes** [comment]
Hah I can do (it actually deliberately isn't licensed right now - it was scratching a personal itch, and I avoid licensing those to avoid accidentally creating a support burden)

**Comment by srichardbd** [comment]
> Hah I can do (it actually deliberately isn't licensed right now - it was scratching a personal itch, and I avoid licensing those to avoid accidentally creating a support burden)

thanks! hopefully the support burden is not too large to carry. I opened a PR with an example MIT license if that is helpful.

**Comment by endocrimes** [comment]
No worries - I can't promise I'll get to them quickly, but feel free to open up PRs if things broke in the last few years :sweat_smile:
